[tool.ruff]

# https://beta.ruff.rs/docs/rules/
select = [
    "B023",
    "B033",
    "C",
    "COM",
#    "D100",
#    "D101",
#    "D102",
#    "D103",
    "D208",
    "D209",
    "D300",
    "E",
    "F",
    "G201",
    "G202",
    "I",
    "PERF102",
    "PIE810",
    "PLC0414",
    "PLW0120",
    "Q",
    "RSE102",
    "RUF013",
    "S113",
    "SIM115",
    "SIM201",
    "SIM210",
    "SIM300",
    "SIM401",
    "TRY302",
    "UP",
    "W",
]

ignore = [
#    "C408",
#    "E711",
#    "E712",
#    "F821",
#    "F841",
#    "F842",
#    "W605",
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = [
    "A", "B", "C", "D", "E", "F", "G", "I", "N", "Q", "S", "T", "W", "ANN", "ARG", "BLE", "COM",
    "DJ", "DTZ", "EM", "ERA", "EXE", "FBT", "ICN", "INP", "ISC", "NPY", "PD", "PGH", "PIE", "PL",
    "PT", "PTH", "PYI", "RET", "RSE", "RUF", "SIM", "SLF", "TCH", "TID", "TRY", "UP", "YTT"
]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

line-length = 100

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

target-version = "py311"

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "double"

[tool.ruff.per-file-ignores]
"alembic/*.py" = ["D", "E501"]
"pymongo_migrations/*.py" = ["D"]
"shared/db_models/*.py" = ["D", "E501"]
"shared/flat_quotes_24h/*.py" = ["D", "E501"]
"providers/xbet/xbet_quote_names.py" = ["E501"]
"providers/betus/betus_payload.py" = ["E501"]
"providers/betboom/betboom_graphql_queries.py" = ["E501"]
"providers/*constants.py" = ["E501"]

[tool.ruff.isort]
known-third-party = ["alembic"]

force-wrap-aliases = true
combine-as-imports = true
