"""test running migrations

Revision ID: 01a04ede9910
Revises: c95b64ab5f3a
Create Date: 2023-08-06 10:01:13.780530

"""


# revision identifiers, used by Alembic.
revision = '01a04ede9910'
down_revision = 'c95b64ab5f3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
