"""test running migrations

Revision ID: 03141c307444
Revises: 833cea0fe018
Create Date: 2023-08-06 14:50:39.724356

"""


# revision identifiers, used by Alembic.
revision = '03141c307444'
down_revision = '833cea0fe018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
