"""test running migrations

Revision ID: 18e304143894
Revises: 9dda5e0b0493
Create Date: 2023-08-23 09:39:32.867054

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '18e304143894'
down_revision = '9dda5e0b0493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
