"""test running migrations

Revision ID: 1a2e75174cd9
Revises: 293fc031f110
Create Date: 2023-08-06 15:06:31.270027

"""


# revision identifiers, used by Alembic.
revision = '1a2e75174cd9'
down_revision = '293fc031f110'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
