"""test running migrations

Revision ID: 2848e6c0ee84
Revises: d03f6508e600
Create Date: 2023-08-06 10:04:19.141583

"""


# revision identifiers, used by Alembic.
revision = '2848e6c0ee84'
down_revision = 'd03f6508e600'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
