"""test running migrations

Revision ID: 293fc031f110
Revises: 2d64e9105d29
Create Date: 2023-08-06 14:54:17.100677

"""


# revision identifiers, used by Alembic.
revision = '293fc031f110'
down_revision = '2d64e9105d29'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
