"""test running migrations

Revision ID: 2d64e9105d29
Revises: f79863a9d09d
Create Date: 2023-08-06 14:53:13.262919

"""


# revision identifiers, used by Alembic.
revision = '2d64e9105d29'
down_revision = 'f79863a9d09d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
