"""test running migrations

Revision ID: 5fc0a3179241
Revises: fa155055c8b7
Create Date: 2023-08-06 15:31:23.763473

"""


# revision identifiers, used by Alembic.
revision = '5fc0a3179241'
down_revision = 'fa155055c8b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
