"""test running migrations

Revision ID: 833cea0fe018
Revises: 2848e6c0ee84
Create Date: 2023-08-06 10:04:41.784135

"""


# revision identifiers, used by Alembic.
revision = '833cea0fe018'
down_revision = '2848e6c0ee84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
