"""test running migrations

Revision ID: 9dda5e0b0493
Revises: e46bd2846f06
Create Date: 2023-08-06 15:36:00.866167

"""


# revision identifiers, used by Alembic.
revision = '9dda5e0b0493'
down_revision = 'e46bd2846f06'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
