"""test running migrations

Revision ID: bb55c491c0c7
Revises: 1a2e75174cd9
Create Date: 2023-08-06 15:07:07.611869

"""


# revision identifiers, used by Alembic.
revision = 'bb55c491c0c7'
down_revision = '1a2e75174cd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
