"""test running migrations

Revision ID: c95b64ab5f3a
Revises: d43b53b62a43
Create Date: 2023-08-06 10:00:47.040553

"""


# revision identifiers, used by Alembic.
revision = 'c95b64ab5f3a'
down_revision = 'd43b53b62a43'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
