"""test running migrations

Revision ID: d03f6508e600
Revises: ee5bba5e6cba
Create Date: 2023-08-06 10:02:26.622187

"""


# revision identifiers, used by Alembic.
revision = 'd03f6508e600'
down_revision = 'ee5bba5e6cba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
