"""test running migrations

Revision ID: d10c0f875f4f
Revises: 03141c307444
Create Date: 2023-08-06 14:50:59.864810

"""


# revision identifiers, used by Alembic.
revision = 'd10c0f875f4f'
down_revision = '03141c307444'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
