"""test running migrations

Revision ID: dfba2b33d0b3
Revises: d10c0f875f4f
Create Date: 2023-08-06 14:51:45.133995

"""


# revision identifiers, used by Alembic.
revision = 'dfba2b33d0b3'
down_revision = 'd10c0f875f4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
