"""test running migrations

Revision ID: e46bd2846f06
Revises: 5fc0a3179241
Create Date: 2023-08-06 15:32:31.031102

"""


# revision identifiers, used by Alembic.
revision = 'e46bd2846f06'
down_revision = '5fc0a3179241'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
