"""test running migrations

Revision ID: ee5bba5e6cba
Revises: 01a04ede9910
Create Date: 2023-08-06 10:01:47.384763

"""


# revision identifiers, used by Alembic.
revision = 'ee5bba5e6cba'
down_revision = '01a04ede9910'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
