"""test running migrations

Revision ID: f79863a9d09d
Revises: dfba2b33d0b3
Create Date: 2023-08-06 14:52:13.844696

"""


# revision identifiers, used by Alembic.
revision = 'f79863a9d09d'
down_revision = 'dfba2b33d0b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
