"""test running migrations

Revision ID: fa155055c8b7
Revises: bb55c491c0c7
Create Date: 2023-08-06 15:07:50.196303

"""


# revision identifiers, used by Alembic.
revision = 'fa155055c8b7'
down_revision = 'bb55c491c0c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
