"""create column hashed_password

Revision ID: 151bd6318aad
Revises: 8b400d97abd7
Create Date: 2023-08-07 09:26:05.767006

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '151bd6318aad'
down_revision = '8b400d97abd7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
