"""test running migrations

Revision ID: 5fd124fb2b85
Revises: e0f0f2aa46f0
Create Date: 2023-08-23 09:27:39.647406

"""


# revision identifiers, used by Alembic.
revision = '5fd124fb2b85'
down_revision = 'e0f0f2aa46f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
