"""test running migrations

Revision ID: 90b5c4829f2f
Revises: ef777d4b2efc
Create Date: 2023-08-23 09:37:11.090139

"""


# revision identifiers, used by Alembic.
revision = '90b5c4829f2f'
down_revision = 'ef777d4b2efc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
