"""test running migrations

Revision ID: b43d24b31bf5
Revises: 151bd6318aad
Create Date: 2023-08-23 09:24:03.439153

"""


# revision identifiers, used by Alembic.
revision = 'b43d24b31bf5'
down_revision = '151bd6318aad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
