"""test running migrations

Revision ID: e0f0f2aa46f0
Revises: b43d24b31bf5
Create Date: 2023-08-23 09:25:01.080811

"""


# revision identifiers, used by Alembic.
revision = 'e0f0f2aa46f0'
down_revision = 'b43d24b31bf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
